# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            SamPages
tagline:          'A personal Blog'
description:      'This is a test intro to be displayed on th front page'
url:              http://samarthasthana.github.io
baseurl:          /

author:
  name:           'Samarth'
  url:            https://www.linkedin.com/pub/samarth-asthana/14/470/7a4

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/samarthasthana
