# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            SamPages
tagline:          'A personal Blog'
description:      'This blog belongs to Samarth Asthana, a youngish developer working his way to quench curiosity and achieve greatness while being rooted to his values and caring for others. Emo much :P?'
url:              http://samarthasthana.github.io
baseurl:          /

author:
  name:           'Samarth'
  url:            https://www.linkedin.com/pub/samarth-asthana/14/470/7a4

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/samarthasthana
